project:
  type: website
  render:
    - index.qmd
    - published/*.qmd
  pre-render:
    - scripts/render-db2pq-test.sh
  resources:
    - published/*.pdf

website:
  title: "notes"
  navbar:
    right:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: true
