---
title: "Should Call et al. (2018) be retracted?"
author: 
  - name: Ian D. Gow
    orcid: 0000-0002-6243-8409
    email: iandgow@gmail.com
abstract: "This short note examines issues related to Call et al. (2018)."
date: 2023-10-29
date-format: "D MMMM YYYY"
bibliography: papers.bib
title-block-style: plain
csl: jfe.csl
format: 
    pdf:
        toc: false
        number-sections: true
        colorlinks: true
        mainfont: TeX Gyre Pagella
        sansfont: TeX Gyre Pagella
---

@Call:2018aa [p. 123] ("CMSW") "find that whistleblower involvement [in enforcement actions for financial misrepresentation] is associated with higher monetary penalties for targeted firms and employees and with longer prison sentences for culpable executives."
@kuvvet2019few [p. 31] suggests that his "investigations and considerations should move all of us further toward doubt and skepticism about the findings of CMSW."

@Walker:2023 suggests that CMSW was flagged for investigation by the *Journal of Accounting Research* ("JAR").
According to a letter to Kuvvet cited by @Walker:2023, "JAR investigated whether the authors' use of the
OSHA data in their study was dishonest and amounted to scientific misconduct" and "concluded that the authors' use of the OSHA data in their study ... does not amount to scientific misconduct."

@kuvvet2019few does not appear to make an explicit allegation of scientific misconduct and precise basis for a claim by Kuvvet of scientific misconduct by CMSW is unclear from the JAR letter.
However, a reading of @kuvvet2019few suggests that one possible basis for such a claim is that CMSW used a whistleblower data set based on OSHA data that they knew or should have known was problematic.
There is nothing to suggest that Kuvvet was suggesting fabrication or falsification of data by CMSW.

Rather, it seems more plausible that Kuvvet's concern was that @Call:2018aa presented results of "statistically significant" associations that would not hold if a different data set were used.
If so, Kuvvet's allegation is that CMSW engaged in a form of p-hacking [@Gow:2023aa].
As such, it is difficult to disagree with the finding by JAR that there was no scientific misconduct.
While p-hacking is a pernicious practice that completely undermines the premise of the null hypothesis significance testing (NHST) that underlies almost all accounting research, it is beyond doubt a completely acceptable research practice and to suggest that it amounts to academic misconduct would impugn the integrity of empirical accoutning research as a discipline.

Nonetheless, in this piece I will argue that some aspects of CMSW do appear to violate norms in accounting research.
First, CMSW claim to estimating their main regressions using "Poisson pseudo-maximum likelihood" (PPML) techniques, but in fact do no such thing.
Second, CMSW make a number of claims about PPML and suggest that these claims are supported by prior research.
Having reviewed this prior research, it is difficult to any basis for these claims and argue that CMSW should be asked to explain why they believe these claims had merit.

## What is PPML?





## References
