---
title: "Operating leverage"
id: sec-bb68
engine: jupyter
jupyter: python3
author: 
  - name: Ian D. Gow
    orcid: 0000-0002-6243-8409
    email: iandgow@gmail.com
date: 2025-12-22
number-sections: true
format:
  html:
    default
  pdf: 
    include-in-header:
      text: |
        \usepackage[group-digits = integer, group-separator={,}, group-minimum-digits = 4]{siunitx}
        \deffootnote{1.6em}{1.6em}{\thefootnotemark.\enskip}
        \addtokomafont{disposition}{\rmfamily}
        \newcommand{\indexc}[1]{\index{#1@\texttt{#1}}}
    colorlinks: true
    geometry:
      - left=2cm
      - right=2cm
    papersize: a4
    mainfont: TeX Gyre Pagella
    mathfont: TeX Gyre Pagella Math
bibliography: papers.bib
---

My younger daughter is back from her first semester of college and one item on her vacation reading list is [*Expectations Investing*](https://www.expectationsinvesting.com) by Michael J. Mauboussin and Alfred Rappaport.
According to the website for the book, "Mauboussin and Rappaport apply an 'expectations infrastructure' framework to trace the process of value creation from the basic economic forces that shape a company's performance—sales, costs, and investments—to the resulting impact on value drivers."

I'm completely onboard with the value of the expectations infrastructure, not only for investing, but also for managing a business.
In the late 1990s, I worked at Stern Stewart, then a world-leading firm in the business of applying ideas from corporate finance to performance measurement, decision-making, and executive compensation.
I started in the Sydney office shortly after it opened in May 1997 then transferred to the New York office in early 1999.
Much of what Stern Stewart did centred on EVA (economic value-added), a registered trademark for what is also known as economic profit or residual income.

One use for the expectations infrastructure at Stern Stewart was in setting performance targets for executive compensation.
Glossing over many details, we would extract the expected levels of EVA from the stock price and set EVA performance targets based on these.
At times, this approach could be challenging.
For example, I spent a couple of months from August 2000 working on an "EVA recalibration" for ADC Telecommunications, then a manufacturer of telecommunications network equipment based in Eden Prairie, Minnesota.

Apart from the accents and the cold (October felt like winter in New York), my recollection of the details is a bit hazy.
But the idea of an EVA recalibration is that ADCT must have adopted EVA some years prior with EVA targets set for some years into the future, but as time passed, it would necessary 
