---
title: "Valuation methods"
author: Ian D. Gow
date: 2025-04-27
date-format: "D MMMM YYYY"
format:
  pdf: 
    colorlinks: true
    geometry:
      - left=2.5cm
      - right=2.5cm
    papersize: a4
    mainfont: TeX Gyre Pagella
    mathfont: TeX Gyre Pagella Math
bibliography: papers.bib
---

Chapter 10 of @Koller:2020aa---"Frameworks for Valuation"---provides a helpful taxonomy of approaches to valuation of companies.
There are three key dimensions on which the models considered in @Koller:2020aa differ.

 - Cash flow versus economic profit
 - Entity versus proprietary measures of cash flow
 - Approach to tax benefits of debt.
 
For the last item, @Koller:2020aa discusses three approaches.
The first approach ("WACC") incorporates the tax benefits of debt in the weighted average cost of capital.
The second approach is known as adjusted present value ("APV") and essentially treats the tax benefit of debt as a separate set of cash flows to be valued and added to the value of the underlying business.
The third approach (CCF) calculates periodic cash flows as the sum of free cash flows and interest tax shields.
Given certain assumptions, CCF will yield identical results to the other two, so @Koller:2020aa recommends those other approaches.
These assumptions also lead to equivalence of WACC and APV.
Given the complexity introduced by deviation from these assumptions would take me too far astray of my goal here, I ignore this dimension of the taxonomy and focus on the other two dimensions.

# Entity versus proprietary measures of cash flow

@Koller:2020aa do not use the "entity" and "proprietary" terminology, but enterprise discounted cash flow uses the entity method (i.e., valuing the whole enterprise or entity first) and the equity cash flow model applies the proprietary approach.

# Cash flow versus economic profit

While @Koller:2020aa only considers economic profit in conjunction with one variant of the 


# References {-}
