---
title: "Spreadsheets for data collection"
author: 
  - name: Ian D. Gow^[University of Melbourne, [ian.gow@unimelb.edu.au](mailto:ian.gow@unimelb.edu.au)]
    orcid: 0000-0002-6243-8409
    email: iandgow@gmail.com
abstract: "Blah blah"
date: today
date-format: "D MMMM YYYY"
bibliography: papers.bib
title-block-style: plain
csl: jfe.csl
format: 
    pdf:
        toc: false
        number-sections: true
        colorlinks: true
        mainfont: TeX Gyre Pagella
        sansfont: TeX Gyre Pagella
    aft-pdf:
        keep-tex: true
        toc: false
        number-sections: true
        colorlinks: true
        mainfont: TeX Gyre Pagella
        sansfont: TeX Gyre Pagella
---

# Introduction

Karl Broman and Kara Woo wrote an excellent paper ["Data Organization in Spreadsheets"](https://doi.org/10.1080/00031305.2017.1375989) on using spreadsheets for organizing data.

Broman has indicated that the paper focuses on settings where the user of the data is entering the data directly.
However, a very common use case I have encountered is on where I (along with collaborators) will be using the data, but someone else is entering the data.
This note focuses on this scenario.

This note aims to expand on and refine the advice provided by @Broman:2018aa for situations where others---such as data entry specialists or research assistants---are entering data into spreadsheets.
@Broman:2018aa provide a list of twelve recommendations.
In this note, I will provide a set of recommendations specific to the approach I recommend here and then follow those with comments on the recommendations of @Broman:2018aa in light of the different context.

# Data-collection scenarios

As mentioned earlier, @Broman:2018aa is predicated on the user of the data also doing the data entry.
References to things such as `Serum_batch1_2015-01-30.csv`, `Mouse153` and `glucose_6_weeks` suggest a setting of collection of observations and measurements from scientific experiments.

In contrast, a more common setting encountered in my research is that of collecting relatively large amounts of somewhat messy data from documents found on the internet.
Typically, we need people to collect these data because either they are too messy to be collected in an automated fashion with sufficiently low cost and high quality or their collection requires some element of judgement.

Here are some cases where I have used spreadsheets to collect data.

1. Data on director biographies. 
These data were used to support the @Gow:2018aa.
2. 

# My recommendations

## Use Google Sheets

My primary recommendation is to use Google Sheets rather than Excel spreadsheets.
While it seems somewhat less than ideal to recommend an approach that relies on a product from one company, at this time there is no equivalent to Google Sheets in terms of functionality.^[If there is an alternative---or if such a product becomes available at a later date---hopefully much of what I say here will apply to that product.]

From [issue](https://github.com/kbroman/dataorg/issues/5):

I loathe Excel, but I love Google Sheets. 
(If there are alternatives to Google Sheets, please forgive my ignorance.) 
I wonder if some discussion of alternatives to Excel like Google Sheets has a place here.

### Benefits of Google Sheets:

1. With distributed data entry, version control issues go away. These are _huge_ in my experience.
2. One can monitor data entry in real-time. "Please don't put values like `2013-03-23 (need to check)` in the `date` column."
3. Adding data validation on the fly is easy. (I think a reason why we often use spreadsheets is because we don't know what data we want to collect in advance. It's common to add columns, etc. So the idea of setting up a nice Excel spreadsheet with data validation, etc., before starting data entry is often not possible in practice.)
4. Multiple people can enter data at once. (Alternative of different people having different Excel files is painful to even mention.)
5. Data import is easy. Use `googlesheets` package from Jenny Bryan.
6. Data access can be added and removed with ease.
7. Access to data is continuous. No need for "please send me the updated spreadsheet before you go home today, as I'd like to run some numbers."
8. Google Sheets has some functions (e.g., regular expression support) that can facilitate data entry.
9. Data access is ensured. Some Excel spreadsheets I "have" are somewhere on the now-erased computers of long-departed research assistants of colleagues (i.e., gone). Google Sheets documents can always be found (putting the key in code also makes it easier to find them than `C:/Desktop/Best Project Ever/data collection_final_v3_3-4-1997.xls` does with Excel files).
10. I haven't had encoding issues with Google Sheets.






### Distributed monitoring

### Version control



# References {-}
