---
title: "Firm identifiers: A process perspective"
author: Ian D. Gow
date: 2024-06-28
date-format: "D MMMM YYYY"
format:
  html:
    colorlinks: true
  pdf: 
    colorlinks: true
    geometry:
      - left=2.5cm
      - right=2.5cm
    papersize: a4
    mainfont: TeX Gyre Pagella
    mathfont: TeX Gyre Pagella Math
bibliography: papers.bib
---

## Introduction

This short note discusses the topic of **firm identifiers**, which I believe does not receive the attention it should in the training of analysts of business data, whether they be budding academics or future business professionals.^[Weak training of business academics, at least in the field I ended up in (accounting research) extends beyond this topic, of course. I have written about this [elsewhere](https://iangow.github.io/far_book/#incorporation-of-data-analysis-skills).]

In the R code that follows, we will use a number of packages, including packages to connect to a directory of parquet files containing WRDS data.

## Doing it badly: The academic approach

I should make it clear that I do not think that academics try to handle firm identifiers badly, merely that they have very weak or non-existent incentives to do it well.

