project:
  type: default
  render:
    - ibis_to_pq.qmd
    - local_engine_benchmark.qmd
    - local_engine_benchmark_update.qmd
  output-dir: ../_site/db2pq_test

execute:
  cache: true
  freeze: auto
