library(tidyverse)
library(farr)
library(DBI)
db <- dbConnect(duckdb::duckdb(), timezone_out ="America/New_York")
filings <- load_parquet(db, "filings", "edgar")
filings
filings |> mutate(agent_cik = str_sub(accessionNumber, 1, 10))
filings |> mutate(agent_cik = str_sub(accessionNumber, 1, 10)) |> select(accessionNumber, agent_cik)
filings |> mutate(agent_cik = as.integer(str_sub(accessionNumber, 1, 10))) |> select(accessionNumber, agent_cik)
filings |> mutate(agent_cik = as.integer(str_sub(accessionNumber, 1, 10))) |> select(accessionNumber, agent_cik) |> filter(form == "10-K")
filings |> mutate(agent_cik = as.integer(str_sub(accessionNumber, 1, 10))) |> filter(form == "10-K")
filings |> mutate(agent_cik = as.integer(str_sub(accessionNumber, 1, 10))) |> filter(form == "10-K", cik != agent_cik)
filings |> mutate(agent_cik = as.integer(str_sub(accessionNumber, 1, 10))) |> filter(form == "10-K", cik != agent_cik) |> count(agent_cik, sort = TRUE)
filings |> filter(cik == 1193125)
filings |> filter(cik == 1144204)
filings |> filter(cik == 1104659)
filings |> filter(cik == 1047469)
filings |> mutate(agent_cik = as.integer(str_sub(accessionNumber, 1, 10))) |> filter(form == "10-K", agent_cik == 1193125)
