---
title: Business valuation with ITCs
author: Ian D. Gow
date: 2025-05-16
number-sections: true
abstract: >
    More than 100% of shareholders' equity of Sunnova, a solar energy company, can be attributed to value realized from ITCs.
    However, under US GAAP, this value is omitted from any measure of profitability.
    In this note, I show how one can estimate the value of ITCs for Sunnova's shareholders and adjust profits to include this value.
format:
  html:
    default
  typst:
    colorlinks: true
    linkcolor: "#0000FF"
    margin:
      x: 2cm
    papersize: a4
    mainfont: Libertinus Serif
    mathfont: New Computer Modern Math
---

The United States government has used **investment tax credits** (ITCs) as a key policy instrument to promote the development and adoption of renewable energy, such as solar, wind, and geothermal.
ITCs allow taxpayers to deduct a percentage of the cost of installing eligible renewable energy systems from their federal income taxes.
Introduced by the Energy Policy Act of 2005 and augmented and refined by subsequent legislation, ITCs are designed to support the  renewable energy industry by improving project economics.

A challenge with ITCs has been that they are often generated by firms with little or no current federal income tax liability.
For example, Sunnova Energy International Inc. (NYSE: NOVA), a company primarily focused on providing solar energy systems to homeowners and businesses in the United States, generates potential ITCs, but has hundreds of millions of tax losses to be used up before it can benefit directly from ITCs.
In this note, I will use Sunnova as a case study of the valuation of ITCs in solar energy businesses.^[My interest in Sunnova was prompted by a [recent Forbes article](https://www.forbes.com/sites/christopherhelman/2025/04/14/ailing-sunnovas-hidden-spreadsheets-could-reveal-efforts-to-obscure-solar-system-data) regarding issues with its financial reporting.]

This challenge means that ITCs are often monetized through **tax equity financing** in which a sponsor with potential ITCs (such as Sunnova) forms a **tax equity partnership** alongside a **tax equity investor**.^[In practice, the partnership may be formed with a wholly owned subsidiary of Sunnova.
For the purposes of this note, there is no reason to distinguish between the parent and wholly owned subsidiaries, so I conflate these as "Sunnova" or "the sponsor" throughout.]
Both the sponsor and the tax equity investor contribute capital that is used to purchase solar energy assets from the sponsor.
Returns are customized for each investor.
The tax equity investor largely receives the benefits of ITCs and accelerated tax depreciation that occur in the early years of the project, while the sponsor receives most of the profits in later years.
These tax equity partnerships are typically **variable interest entities** (VIEs) that are consolidated for financial reporting purposes by the group comprising the sponsor.

However, estimating the effects of ITCs on the value of the sponsor's equity is complicated by at least two features of the financial reporting for tax equity partnerships.
First, the tax equity investors are considered noncontrolling interests, which means their interest is reflected as part of equity.^[In some cases, the interests of the tax equity investor may be reflected as **redeemable noncontrolling interests**, but this is effectively a form of equity to which all the arguments here apply.]
This means that value transferred to or from sponsor's shareholders to the tax equity investors never shows up as part of net income.
Second, almost all of the direct benefits of the ITCs will not appear anywhere in the financial statements of the consolidated group, as the tax equity partnership does not directly benefit from these.
Rather these are realized in the tax filings (and financial statements) of the tax equity investors.

While the direct benefits of ITCs are not reflected in the financial statements of the sponsor, the ITCs do leave hints of their existence and value in those statements.
The purpose of this note is to show how we can estimate the value created by ITCs using data from these hints.

As will be seen below, the value of Sunnova is dominated by the value of ITCs.
The theoretical value of ITCs generated in each year exceeds the operating profits by a wide margin.
The shareholders' equity of Sunnova is entirely attributable to the value realized from ITCs; that is, apart from the value of ITCs, shareholders' equity would be negative.

While a broader discussion of the policy merits of ITCs is beyond the scope of this note, it does seem that the purpose of ITCs is to encourage investment in renewable energy.
However, if it is extremely difficult for investors to evaluate the investment merits of businesses creating solar energy assets, then the possible virtues of ITCs might be undone by poor financial reporting.

# Value creation at Sunnova

While Sunnova has a surprisingly complex business model, for the purposes of this note, I will split Sunnova's value creation process into two pieces: the solar energy systems themselves and the ITCs these create.^[This split is somewhat arbitrary in that Sunnova could not generate value from the ITCs if it were not "originating" ITCs by installing solar energy systems. This is a bit like the old saw that Costco makes all its money from memberships, as though people would pay for these if Costco were not proving warehouse stores for its members to use. However, the difference here is that, as discussed below, the value of ITCs never hits Sunnova's income statement. I return to this issue below.]

## Value creation with energy systems

Regarding the first piece, Sunnova is involved in the installation, operation, maintenance, and financing of solar energy systems with a view to reducing energy costs for homeowners.
Broadly speaking, Sunnova offers four types of customer agreements.
Customers can choose whether to lease or purchase the system itself or to instead enter into a power purchase agreement (PPA).
A customer who chooses to purchase might pay in cash or use financing provided by Sunnova to pay for it.
Only leases and PPAs give rise to ITCs for Sunnova; when systems are sold to homeowners, it is the homeowners who get a tax credit.^[These tax credits work differently from the ITCs discussed here. When customers use Sunnova to finance their purchases, there may be more opportunity for Sunnova to indirectly benefit from these tax credits. One issue is that many US households would not have the tax capacity to fully benefit from these tax credits.]

One approach to valuing this first piece amounts to valuing the customer agreements themselves.
Doing so is not entirely straightforward for several reasons.
Perhaps the biggest complication arises from the fact that the agreements can have inital terms of up to 25 years with renewal options possibly extending these even further into the future.
While the initial costs of installing systems might be straightforward enough, the value of the contracts will hinge on the anticipated benefits of solar energy many years into the future, along with estimates of the costs of maintaining the systems, the risks of nonpayment by households, the costs incurred to remove systems from customers' premises, and so on.

A second complication arises from the inherent mixing of operating and financing dimensions in the customer contracts and this issue is perhaps exacerbated by the use of securitization vehicles to finance the acquisition of energy systems and customer agreements.
Sunnova cannot succeed just by having a lower cost of installation and maintenance of solar energy systems.
It must also correctly price the financing inherent in the customer agreements, including the risk of nonpayment, and obtain financing at low cost that matches the terms of those agreements.

Furthermore, valuing existing customer agreements does not suffice to value this piece of the Sunnova puzzle.
An investor also needs to understand the value of future customer agreements.
While existing customer agreements can provide a basis for this analysis, it is important to understand developments in the economics and regulation of energy that might affect customers' willingness to pay for Sunnova's systems.
For example, if households have signed up on the basis of being able to sell power back to the grid, then changes to regulations supporting this may reduce customer demand for Sunnova's systems.

From the above, it should be clear that understanding the value of this piece of Sunnova's business is unlikely to be straightforward.
But I will not even attempt to seriously analyze the issues in doing so in this note.
These issues would include grappling with the capital structure of Sunnova, which involves complex securitizations in a model that does not seem sustainable.
Instead I will focus on the issues created by the second piece.

## Value creation from investment tax credits

The federal government provides tax credits for investments in renewable energy such as the solar energy systems like those supplied by Sunnova.
These investment tax credits (ITCs) can range between 6% and 70% of the basis of eligible energy systems owned by Sunnova, such as those covered by customer agreements involving leases and PPAs.
As mentioned above, companies like Sunnova generally do not have taxable income sufficient to absorb the ITCs, so they turn to so-called **tax equity investors** to realize the economic benefits of ITCs.

While the details of **tax equity vehicles** can vary, the basic idea can be conveyed with a description of a typical structure.
There are two investors in a tax equity vehicle and one---the sponsor---can be viewed as "selling" ITCs and the other---the tax equity investor---can be viewed as "buying" the ITCs.

The sponsor and the tax equity investor contribute cash to the partnership that is then used to purchase solar energy systems from the sponsor.
The tax equity vehicle will get income from customer contracts and incur expenses related to operating and maintaining the solar energy systems.
For tax purposes, the solar energy systems will generate ITCs and tax deductions for depreciation at an accelerated rate.^[Tax depreciation is calculated using MACRS ("modified accelerated cost recovery system"), which applies double declining balance over a period prescribed by tax regulations for assets of various types.]

For federal income tax purposes, the tax equity vehicle is a partnership, which generally means it is a "pass-through" entity that does not pay federal income tax.
Instead, it files an information return on IRS Form 1065 reporting the business's total income and deductions, and the allocation of these to the partners.
Each partner receives a Schedule K-1, showing its share of tax income and credits that it then reports on its own tax return.

Tax equity vehicles typically incorporate a **flip**, meaning a contracted shift in the allocation of cash flow rights over time.
Some tax equity vehicles use an **IRR flip** based on a target return for the tax equity investor, while others use a **time flip** that specifies that flip occurs on a specific date.

Before the split, the tax equity investor gets 99% of the tax benefits, including ITCs and depreciation, and some share of the cash flows, while the sponsor gets 1% of tax benefits and the rest of cash flows.^[Presumably tax law prevents the tax equity investor's share of tax benefits being set at 100%.]
After the flip, the share of the tax equity investor drops (say, to a 5--10% share) and the sponsor gets the rest.
Often the sponsor has the right to buy out the tax equity investor's remaining interest after the flip.

The tax equity vehicle can function as a "sale" of the ITCs in that the tax equity investor is willing to receive a much lower pre-tax return on investment than would be the case without the ITCs.
The sponsor pays much less in returns to the tax equity investor than it would pay to an investor taking on similar risk over a similar term without the tax benefits.
Presumably, the tax equity investor receives higher after-tax returns than it would get from an investment with similar risk and duration without tax benefits.

## Estimating the potential value of ITCs

Given the importance of ITCs to the economics of Sunnova, investors need to understand Sunnova's ability to realize these benefits.
A natural starting point is the theoretical value of the ITCs, which is the product of the ITC rate (e.g., 30%) and the tax basis.
As discussed by Sunnova in its 10-K, the ITC rate can range between 6% and 70%" depending on the project's "location ..., its size, its ability to satisfy certain labor and domestic content requirements and the category of consumers it serves."
As Sunnova does not appear to provide any information on the ITC rate in its SEC filings, I assume 30% for the purposes of this note.
Given the critical importance of ITCs for the value of Sunnova, investors might want Sunnova to provide more information on the average ITC rate.

The tax basis of a solar energy system will generally exceed the cost incurred by Sunnova to create it.
When solar energy assets are contributed (in effect, sold) to the tax equity vehicle, their value will be based on an appraisal of their fair market value.
Drawing on Sunnova's 10-K filing, "we sell solar energy systems at a tax gain to our tax equity partnerships. Since the tax equity partnerships are considered variable interest entities [controlled by Sunnova], the tax gain is eliminated upon consolidation under U.S. GAAP.
However, this is a taxable event for income tax purposes.
As such, we recognize the tax expense when the sale occurs."
With a statutory tax rate of 21\%, the *Tax equity activities* disclosed in note 9 for the year ended December 31, 2024, of \$165,094k suggests a gain of $786,162k.^[Sunnova reports amounts in its financial statements in thousands of dollars and I include the "k" suffix to remind readers of this.]
Given that the gross book value of solar energy systems increased by \$1,981,575k, this suggests a mark-up of nearly 40% on original cost.^[Calculated by subtracting the beginning balance for *Solar energy systems and energy storage systems* of \$5,443,796k from the ending balance of \$7,425,371k. See note 3 of Sunnova's 10-K for details.
This calculation may differ from the true mark-up if other items are included in *Tax equity activities* or if *Solar energy systems and energy storage systems* includes assets not transferred to tax equity vehicles.^[Note that the *Tax equity activities* disclosure is new from the 2024 10-K filing suggesting that Sunnova had not been recognizing this deferred tax liability in previous years. Of course, because Sunnova is very unlikely to ever pay income taxes, this liability is largely theoretical interest apart from the information it provides for us to use here.]
An alternative calculation would use property and equipment, net for the VIEs of \$5,827,836k and \$4,273,478k as of December 31, 2024 and 2023, respectively (see the note to the face of Sunnova's balance sheet), and (conservatively) ascribe all depreciation of $229,012k to these assets. This implies additions to solar energy systems of \$1,783,370k and a markup of 44%.]

While we can make an educated guess about one part of the theoretical value of the ITCs, we have little information on the ITC rate enjoyed by Sunnova.
If we assume 30%, then we have a theoretical value of ITCs generated in 2024 of \$830,321k.^[That is, $830{,}321 = 30\% \times (786{,}162 + 1{,}981{,}575)$.]
Given that this theoretical value compares with $839,922k in total revenue for 2024 from loss-making operating business, we can perhaps consider Sunnova to be in the ITC business as much anything else.
Full realization of the theoretical value of ITCs might turn Sunnova from a loss-making, seemingly insolvent, operation to a pretty profitable outfit.
As such, understanding the realization of value from ITCs is core to valuing Sunnova's equity.^[I am simply ignoring the additional value of MACRS depreciation for tax purposes, though a complete analysis would need to ascribe some value to it.
Plausibly the ITCs are the biggest piece of the tax puzzle.]

As of December 31, 2024, the tax equity partnerships held \$5,827,836k in property and equipment, net, which is a large share of the \$7,425,371k reported under *Solar energy systems and energy storage systems* for the Sunnova group.
If we assume that all accumulated depreciation (\$788,083k) relates to this latter amount and ascribe a proportionate share to the former we have \$6,446,367k in original cost of solar energy system transferred to VIEs.^[That is, $6{,}446{,}367 = 5{,}827{,}836 + 788{,}083 \times 5{,}827{,}836 \div 7{,}425{,}371$.]
Adding a markup of 40% and applying an ITC rate of 30% yields \$2,707,473k as the estimated potential ITC value for assets transferred to tax equity parnerships over time.^[Why are there solar energy assets that have not been included in tax equity partnerships?
First, two early tax equity partnerships appear to have wrapped up by the end of 2024.
Second, some assets would not be eligible for ITCs and so may not have been included in transfers to tax equity parnerships.
For example, historically energy storage systems with associated solar energy systems were ineligible for ITCs.
Third, it seems that it took some time for Sunnova to use tax equity parnerships.
This can be seen by the presence of deferred tax assets of \$313,329 disclosed in note 9 of Sunnova's financial statement, which would be consistent with about $1 billion of ITCs having been retained by Sunnova (and likely lost).
While Sunnova would pick up ITCs as part of its 1% of the pre-flip value of tax entity partnerships, this would only explain a small fraction of the deferred tax asset balance.
Note that Sunnova records a valuation allowance that zeroes out any deferred tax assets on its balance sheet.]

## Factors affecting realized value of ITCs

The potential or theoretical value of ITCs is important, but the realized value for Sunnova's shareholders might be much lower.
First, the tax equity partnership might not be particularly *efficient* for various reasons.^[Here I am using "efficiency" in a sense similar to that used in engineering: how much actual tax savings can be realized as a fraction of the potential tax savings provided to the tax equity partnership?]
Second, some value will need to be shared with the tax equity partners.

The first potential inefficiency relates to the legal and administrative costs of setting up and running the tax equity partnership.^[Complicating matters, the Inflation Reduction Act of 2022 (or IRA) allows for the transfer of ITCs and from note 9 of its 10-K, it appears that Sunnova has sold ITCs in 2023 and 2024. Details on how the ITC sales worked seem scant.
However, these transfers were likely affected by pre-existing contractual commitments to tax equity investors and additionally Sunnova would have had an interest in generating the mark-up discussed above before selling these ITCs.]
In addition, there are frictions arising from the need for the tax equity investor to understand (to some extent) the economics of the assets being sold to the tax equity vehicle, as this investor's payoff is likely to be affected to some extent by the operating cash flows of the partnership.
While it might be most efficient for the tax equity investor to provide debt financing to the partnership, tax law precludes this.
Nonetheless, the parties are likely to strive to make the "equity" investment in the partnership as debt-like as is possible within the constraints of tax law using devices such as "truing-up" when cash flows fall short of expectations.
On top of this, by limiting the share of ITCs for the tax equity investor to 99\%, the other 1\% is effectively lost.
Another concern may be moral hazard.
For example, the tax investor would want to ensure that contracts between the partnership and Sunnova itself are fair to the partnership.^[It seems plausible that the partnerships purchase services from Sunnova.]

In addition to any potential efficiency loss, Sunnova is likely to need to offer a *share of ITC value* to the tax equity investors.
In its 10-K, Sunnova says that, "with respect to tax equity and tax credit sales, there are a limited number of potential tax equity investors and purchasers of ITCs, and the competition for this investment capital is intense."
While Sunnova might be a sophisticated repeat player when it comes to structuring tax equity vehicles, it seems likely that a significant fraction of the value of ITCs needs to be shared with the tax equity investors.

A final concern might be that the IRS will object to the 40% mark-up embedded in the fair market value (FMV) used as the tax basis for ITCs.
Disclosures in Sunnova's 10-K filings suggest that the tax equity investors seek indemnities from Sunnova for this risk:
"If the IRS or the U.S. Treasury Department makes a determination that the fair market value of our solar energy systems is materially lower than what we have reported in our tax equity vehicles' tax returns, we may have to pay significant amounts to our tax equity vehicles, our tax equity investors, tax credit buyers and/or the U.S. government. Such determinations could have a material adverse effect on our business and financial condition."
Of course, these indemnities depend on Sunnova being a viable entity when the IRS comes knocking.

Now that we understand the economics of tax equity vehicles and ITCs, the next question is: To what extent can we glean the information to assess the components of the value of ITCs to Sunnova from its financial reporting?

## Estimating the realized value of ITCs

Estimating the value realized for Sunnova's shareholders from the consolidated financial statements of Sunnova.
I argue that this difficulty arises from two aspects of GAAP.
First, GAAP takes a strong entity perspective that obscures the sharing of value between tax equity investors and Sunnova's shareholders who effectively provide the sponsor equity to the tax equity vehicles.
Second, much of the value creation from ITCs is entirely omitted from the books of the Sunnova group.

### Noncontrolling interests

From the perspective of GAAP, the tax entity partnerships are **variable interest entities** controlled by Sunnova.
As such they are fully consolidated by the Sunnova group for financial reporting purposes.
If the tax entity partnerships are efficient, they should have little impact on the running of Sunnova's business (systems are installed and maintained just as they would be without tax entity partnerships, and customers are billed and pay as they would otherwise).

The tax equity investors are treated as noncontrolling interests (NCI).
Depending on the tax equity vehicle, the NCI will be redeemable or not.
A portion of Sunnova's net income will be allocated to NCI and the rest to Sunnova's stockholders.
At the same time, portions of Sunnova's net assets will be allocated to redeemable NCI, to NCI and the rest to
stockholders' equity.

Where things start to get complicated is in the allocation of income between NCI (tax equity investor) and Sunnova's shareholders (sponsor).
As discussed above, in some sense we want to extract information about the pretax cash flows for each VIE so that we could calculate the pre-tax return provided to the associated tax equity investor and compare that with the pre-tax return Sunnova would expect to pay to an investor faced with the same risk and maturity profile, but no tax benefits.
It's the dollar value of this difference that reflects the value of the ITCs realized by Sunnova's shareholders.
While it is difficult to assess the pre-tax return Sunnova would expect to pay to an investor faced with the same risk and maturity profile using information provided in the financial statements, we make a conservative estimate of the value of the ITCs realized by Sunnova's shareholders if we assume that this is zero.^[This estimate will be conservative because it will be lower than we would estimate if we assumed that the appropriate pre-tax return without ITCs were, say, 5%.]
Of coure, assuming zero expected return on "equity" provided by NCI is entirely consistent with the traditional approach of financial accounting standards which is to ignore the cost of equity capital.

Because almost all the direct benefits from ITCs flow to the tax equity investor on its own tax return, these are not reflected directly anywhere in the consolidated financial statements of the Sunnova group.^[While the Inflation Reduction Act of 2022 (or IRA) allows for the transfer of ITCs and from note 9 of its 10-K, it appears that Sunnova has sold ITCs in 2023 and 2024, it appears that most of these transfers were implemented via the tax equity structures already in place. Discussion in note 2 of Sunnova's 10-K suggests that, while the portion of ITC sales are recorded as increases in NCI, these do not flow through net income. The portion attributable to Sunnova's shareholders does flow through the income statement as a reduction in income tax expense.]
But looking at the "consolidated statement of redeemable noncontrolling interests and equity" over time provides useful information.^[Calculations underlying numbers reported in this section can be found in a spreadsheet [here](https://docs.google.com/spreadsheets/d/1z8Fn_Bz8iT6wkEG6eLBzfOJPOG4Dr4V4U71D11D6Ttw/edit?usp=sharing).]
Since January 1, 2018, tax equity investors have contributed a total of \$3,260,966k, received cash flows of \$786,879k, and seen their share of equity increase by \$814,859k, partly through attribution of net income of \$194,291k to NCI.^[The share of equity attributable to NCI is the result of of applying the "hypothetical liquidation at book value ('HLBV') method, [under which] the amounts reported as noncontrolling interests in the Consolidated Balance Sheets represent the amounts third-party investors would hypothetically receive at each balance sheet date under the liquidation provisions of the operating agreements, assuming the net assets of the subsidiaries were liquidated at amounts determined in accordance with GAAP and distributed to the investors."
For the purposes of this note, I put evaluation of the usefulness of HLBV-based information outside the scope of this note.]

Balancing the NCI equation is the transfer from NCI to retained earnings ("accumulated deficit") to the tune of $1,853,519k.^[Comparing this number with the theoretical value of ITCs reported above suggests that Sunnova is realizing a sizeable portion of that value.
However, we need to be careful here, as this transfer would also include some value realized from accelerated depreciation, which is omitted from the theoretical value calculation I made above.]
These transfers from NCI are how Sunnova's shareholders see benefits from tax equity partnerships.
However, because transfers between NCI and stockholders' equity are not considered income, these never touch the income statement under GAAP.
Assuming that the HLBV-based numbers adequately reflect the share of value with NCI, we can calculate an "adjusted" net net income attributable to stockholders along the lines shown in @tbl-adj.

|                                                         | 2021      | 2022      | 2023      | 2024      |
| --------------------------------------------------------| ---------:| ---------:| ---------:| ---------:|
| Net (loss) attributable to stockholders                 | $-138{,}128$ | $-161{,}642$ | $-417{,}961$ | $-367{,}893$ |
| Transfers from NCI                                      | 207,153   | 256,575   | 554,160   | 643,065   |
| Adjusted net income attributable to stockholders        | 69,025    | 94,933    | 136,199   | 275,172   |

: Adjusting net income for transfers from NCI (\$ thousands) {#tbl-adj tbl-colwidths="[48,13,13,13,13]"}

Note that the analysis above focuses on the value of ITCs generated to date.
Just as we need to value future customer agreements to value the first piece of the Sunnova value puzzle, we also need to think about future ITCs to value the second piece.
Unfortunately, Sunnova cannot generate ITCs without acquiring and running solar energy assets and all evidence to date suggest that Sunnova might lose all the money it makes in ITCs in acquiring and running solar energy assets.
While the adjusted numbers suggest that Sunnova is making money on an "adjusted GAAP" basis, this follows years in which it has lost money even on an adjusted basis.
And if the GAAP numbers prove to be optimistic in terms of customer renewal rates, the collectibility of receivables, operating and maintenance expenses, or the costs of removing systems, there is no margin for error enjoyed by Sunnova's shareholders.^[While some risk is shared with investors in securitization vehicles, the accounting for these claims as liabilities suggest that these risks largely fall on the shoulders of Sunnova's shareholders.]
Of course, another issue is the continued availability of ITCs under future legislation.^[See ["Republican tax cut plan would gut US clean energy"](https://on.ft.com/3GPqXod) in the May 12, 2025 issue of the *Financial Times*.]

### Evaluation of GAAP

In the United States of America, accounting standards issued by the Financial Accounting Standards Boards (FASB) form the core of generally accepted Generally Accepted Accounting Principles (GAAP).
According to the FASB's [Concept Statement No. 8](https://www.fasb.org/standards/concept-statements), "the objective of general purpose financial reporting  is to provide financial information about the reporting entity that is useful to existing and potential investors, lenders, and other creditors in making decisions about providing resources to the entity."
It is far from clear that GAAP is providing the information needed by investors in this context, though some adjustments can be made to glean greater insights.

By focusing on the consolidated group, GAAP provides information about an entity that no-one is interested in.
The information reported for NCI is useless for the noncontrolling investors, as it includes all sorts of risks that are of no concern to them while including no information about the tax credits that motivate their investment in the first place.
The information reported for Sunnova's shareholders is also far from useful, as the reported income statement completely neglects the value derived from ITCs "sold" to tax equity investors.
