---
title: "Response to editor's comments on previous version"
author: 
  - name: Ian D. Gow^[University of Melbourne, [ian.gow@unimelb.edu.au](mailto:ian.gow@unimelb.edu.au)]
    orcid: 0000-0002-6243-8409
    email: iandgow@gmail.com
date: today
date-format: "D MMMM YYYY"
bibliography: papers.bib
title-block-style: plain
csl: jfe.csl
format: 
    pdf:
        toc: false
        number-sections: true
        colorlinks: true
        mainfont: TeX Gyre Pagella
        sansfont: TeX Gyre Pagella
---

1. (p. 1): It would be nice to reproduce here one of more pictures from this wikipedia page (I suppose they are freeware commons).

Happy for one to be included.

2. (p.5): This is a very important point especially for editorial processes.

OK.

3. (p. 7): Please clarify this technical expression at least in a footnote 

Done.

4. (p. 10): Perhaps a simple example or a plain explanation of these strategies may help here to enhance clarity.

Added some discussion of the strategies in common use.

5. (p. 10): You may explain this assumption as follows (or equivalent working): This assumption "requires that in the absence of treatment, the difference between the ‘treatment’ and ‘control’ group is constant over time."

Added something like that.

6. (p. 11): My own commentary argues exactly for this extension of possible research focus.
On the one hand, qualitative research including description of phenomena.
On the other hand, comparative theoretical research focusing to conceptual frameworks and normative alternatives 
I can share my draft if you are willing to read and perhaps refer to it.

If you feel a citation makes sense, happy for you to add "see X" or similar.
