---
title: "On Genius"
author: 
  - name: Ian D. Gow^[University of Melbourne, [ian.gow@unimelb.edu.au](mailto:ian.gow@unimelb.edu.au)]
    orcid: 0000-0002-6243-8409
    email: iandgow@gmail.com
date: 2024-01-04
date-format: "D MMMM YYYY"
bibliography: papers.bib
abstract: "In this short note, I try to provide a guide to appreciating Ball and Brown (1968) (and learning something about research along the way)."
title-block-style: plain
csl: jfe.csl
format: 
    pdf:
        toc: false
        number-sections: true
        colorlinks: true
        mainfont: TeX Gyre Pagella
        sansfont: TeX Gyre Pagella
    docx:
        number-sections: true
---

## On genius

Recently I re-watched *Adaptation* (2001) with my younger daughter, Gemma.
At one level, *Adaptation* is the screen adaptation of a 1998 non-fiction book *The Orchid Thief* by Susan Orlean, itself a book-length adaptation of a piece she wrote for *New Yorker* magazine in 1995.^[See [here](https://en.wikipedia.org/wiki/The_Orchid_Thief) for details.]

For me, there is something exhilarating about the work of Charlie Kaufman, who both wrote the adaptation of Orlean's book and (in some sense) served as the main character in that adaptation.
I think much of this excitement comes from (sometimes fleeting) appreciation of the genius of his work, part of which is reflected in the many levels at which Kaufman's screenplays seem to operate. 
Watching *Adaptation* for the umpteenth time, I was struck by the scene in a pub in which screenwriting guru Robert McKee (portrayed by Brian Cox) tells Charlie (played by Nicholas Cage) what he needs to do to finish the movie.
The scene begins with a reading from Orlean's book and ends 113 seconds later with an homage to *Casablanca*.
In the meantime, the scene does so much more.
It marks the shift to the dramatic third act of the movie, while also foreshadowing what that will be, and at the same time explaining (after a fashion) why the movie turns the way it does.
But it also manages genuine poignancy (and character development), as Charlie embraces McKee, both literally and figuratively.

But where would one find genius in the field that is (notionally) my own?^[I say "notionally" because I've felt rather estranged from my academic field for a long time now. For some of the reasons why, see ["The Elephant in the Room: p-hacking and Accounting Research](https://doi.org/10.1515/ael-2022-0111)".]
To me, the best example is Ball and Brown (1968).

But genius can pass by unnoticed or be difficult to appreciate if 
One can enjoy *Adaptation* as an off-the-wall action movie.

Visiting the zoo.

Start with FFJR:

 1. Read paper
 2. Read chapter
 3. Watch video
 
Then BB68:

  1. Read paper
  2. Read chapter
  
  Ray or Phil?
