---
title: "Valuation methods"
author: Ian D. Gow
date: 2025-04-30
date-format: "D MMMM YYYY"
format:
  pdf: 
    colorlinks: true
    geometry:
      - left=2.5cm
      - right=2.5cm
    papersize: a4
    mainfont: TeX Gyre Pagella
    mathfont: TeX Gyre Pagella Math
bibliography: papers.bib
---

Chapter 10 of @Koller:2020aa---"Frameworks for Valuation"---provides a helpful taxonomy of approaches to valuation of companies.
There are three key dimensions on which the models considered in @Koller:2020aa differ.

 - Cash flow versus economic profit
 - Entity versus proprietary measures of cash flow
 - Approach to tax benefits of debt.
 
For the last item, @Koller:2020aa discusses three approaches.
The first approach ("WACC") incorporates the tax benefits of debt in the weighted average cost of capital.
The second approach is known as adjusted present value ("APV") and essentially treats the tax benefit of debt as a separate set of cash flows to be valued and added to the value of the underlying business.
The third approach (CCF) calculates periodic cash flows as the sum of free cash flows and interest tax shields.
Given certain assumptions, CCF will yield identical results to the other two, so @Koller:2020aa recommends those other approaches.
These assumptions also lead to equivalence of WACC and APV.
Given the complexity introduced by deviation from these assumptions would take me too far astray of my goal here, I ignore this dimension of the taxonomy and focus on the other two dimensions.

# Entity versus proprietary measures of cash flow

@Koller:2020aa do not use the "entity" and "proprietary" terminology, but enterprise discounted cash flow uses the entity approach (i.e., valuing the whole enterprise or entity first) and the equity cash flow model applies the proprietary approach.
While the terms "entity" and "proprietary" have their heritage in a stream of accounting thought unfamiliar to modern accounting academics, they seem useful nonetheless.

In the context of valuation, the proprietary approach is perhaps easiest to explain.
The proprietary approach requires forecasting cash flows to holders of the residual equity claim and then discounting these at an appropriate rate to calculate a value of that equity claim.
Simple!
The phrase "an appropriate rate" is doing a lot of heavy lifting here.
Standard finance theory would suggest that, even with assets with fixed risk attributes, the appropriate discount rate will be a function of leverage and the timing of the cash flows.

A core idea of finance is that it is the risk attributes of assets that drive expected returns rather than how those assets are financed.
Practitioners will often make claims such as "entity $X$ has a lower cost of capital than other entities so it can afford to discount operating asset $Z$ at a lower rate."^[Here I assume that there are no operating synergies between the asset $Z$ and other assets of entity $X$. I will explain the term "operating" in a moment.]
One corollary of such a claim is that $X$ will value asset $Z$ more than other entities.
Such claims are often predicated on the idea that assets can be financed with debt (e.g., "Entity X can borrow at $y\%$, so we should discount cash flows at $y\%$").

Such claims are *not* endorsed by standard finance theory.
While the classic reference is @Modigliani:1958aa, an extensive literature has refined the Modigliani-Miller framework and @Koller:2020aa provides excellent discussion of the topic.
@Modigliani:1958aa speaks of the concept of "a firm" and generally equates a firm as comprising "physical assets" financed by equity and debt.
However, reality can be more complex.

First, a firm might comprise shares in other firms and interests in partnerships and joint ventures.
Accountants have grappled with the practical issues related to defining "a firm" for many decades resulting in standards such as IFRS 10, which requires the presentation of **consolidated financial statements** for a **group**, which can be considered as practical notion of the firm in real-world economic situations.
For the purposes of this note, I will shelve the complexities here and assume that we have a simple single-company business.

Second, few (if any) businesses today can be viewed as the operation of physical assets financed by debt and equity.
Physical assets are only a fraction of the reported balance sheets of most firms today, with financial and intangible assets being increasingly important.^[Additionally, it is widely recognized that many intangible assets are either undervalued or completely missing from reported balance sheets due to limitations of the governing accounting standards.]
Often financial assets will be managed as part of the financial strategy of the firm and thus, for reasons to be discussed shortly, are best considered in conjunction with debt rather than being valued with other assets of the business.

Similarly, the claims on a firm's assets will not be limited to debt and equity.
Firms will have obligations to customers, employees, and suppliers arising out of the ordinary course of business and it is generally inappropriate to value these in the same way one might value claims such as debt and equity.
Also, firms will often have obligations (i.e., liabilities) that are best thought of as debt-like claims on the business.^[Another issue is that firms may have liabilities that are missing from the balance sheet. Fortunately accounting standards are generally **conservative** and this means that they are much less inclined to permit unreported or understated liabilities than is the case with assets.
In the past, firms obligations for pensions and other post-retirement benefits and leases were understated, but accounting standards have generally moved to close such gaps over time.]

Putting aside issues of missing or misvalued assets and liabilities, we can repurpose the balance sheet equation for valuation purposes.
This has assets equal to liabilities and shareholders' equity:

$$ A = L + SE $$

It is important to note that this relation is an **accounting identity** not simply a model that might be approximately true.
We can break down the assets and liabilities into operating and financing resulting in the following:

$$ OA + FA = OL + FL + SE $$
where $OA$ and $FA$ are operating and financing assets, respectively, and $OL$ and $FL$ are operating and financing liabilties, respectively.

We can rearrange terms to get 

$$ OA  - OL = (FL - FA) + SE $$
A standard building block in the entity approach as discussed in @Koller:2020aa is **free cash flow**, which is defined as the "the after-tax cash flow that would be generated if the company ... financed the business entirely with equity" [@Koller:2020aa, p. 209].
With all-equity financing and denoting **net operating assets** as $\textit{NOA}$, we have:

$$ \textit{NOA} = OA  - OL = SE $$
The **clean surplus assumption** requires that changes in $SE$ relate with to net income ($NI$) or dividends $D$:

$$ \Delta SE = NI - D $$

But $\Delta SE = \Delta \textit{NOA}$, so

$$ D = NI - \Delta \textit{NOA} $$
Because there are no financial assets or liabilities, net income is the same as **net operating profit after tax** or NOPAT.

$$ D = \textit{NOPAT} - \Delta \textit{NOA} $$

# Cash flow versus economic profit

While @Koller:2020aa only considers economic profit in conjunction with one variant of the 


# References {-}
